# Written by allen.stevens
# used to replace words with ports in ACE
UDP_PORTS = {'non500-isakmp': '4500',
             'netbios-dgm': '138',
             'pim-auto-rp': '496',
             'nameserver': '42',
             'netbios-ns': '137',
             'netbios-ss': '139',
             'mobile-ip': '434',
             'snmptrap': '162',
             'discard': '9',
             'bootpc': '68',
             'bootps': '67',
             'domain': '53',
             'isakmp': '500',
             'sunrpc': '111',
             'syslog': '514',
             'tacacs': '49',
             'dnsix': '195',
             'xdmcp': '177',
             'biff': '512',
             'echo': '7',
             'snmp': '161',
             'talk': '517',
             'tftp': '69',
             'time': '37',
             'ntp': '123',
             'rip': '520',
             'who': '513'}

TCP_PORTS = {'pim-auto-rp': '496',
             'ftp-data': '20',
             'hostname': '101',
             'chargen': '19',
             'daytime': '13',
             'discard': '9',
             'domain': '53',
             'finger': '79',
             'gopher': '70',
             'klogin': '543',
             'kshell': '544',
             'sunrpc': '111',
             'syslog': '514',
             'tacacs': '49',
             'telnet': '23',
             'ident': '113',
             'login': '513',
             'whois': '43',
             'echo': '7',
             'exec': '512',
             'nntp': '119',
             'pop2': '109',
             'pop3': '110',
             'smtp': '25',
             'talk': '517',
             'time': '37',
             'uucp': '540',
             'bgp': '179',
             'cmd': '514',
             'ftp': '21',
             'irc': '194',
             'lpd': '515',
             'www': '80'}

ICMP_TYPES = {'administratively-prohibited': '3 13',
              'host-precedence-unreachable': '3 14',
              'precedence-unreachable': '3 15',
              'host-tos-unreachable': '3 12',
              'protocol-unreachable': '3 2',
              'router-advertisement': '9',
              'dod-host-prohibited': '3 10',
              'information-request': '15',
              'net-tos-unreachable': '3 11',
              'router-solicitation': '10',
              'source-route-failed': '3 5',
              'dod-net-prohibited': '3 9',
              'alternate-address': '6',
              'information-reply': '16',
              'parameter-problem': '12',
              'timestamp-request': '13',
              'host-unreachable': '3 1',
              'port-unreachable': '3 3',
              'net-unreachable': '3 0',
              'network-unknown': '3 6',
              'timestamp-reply': '14',
              'packet-too-big': '3 4',
              'host-isolated': '3 8',
              'source-quench': '4',
              'time-exceeded': '11',
              'host-unknown': '3 7',
              'mask-request': '17',
              'unreachable': '3',
              'echo-reply': '0',
              'mask-reply': '18',
              'traceroute': '30',
              'redirect': '5',
              'echo': '8'}

ALL_PORTS = {'tcp': TCP_PORTS,
             'udp': UDP_PORTS,
             'icmp': ICMP_TYPES}
